name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: ConorMacBride/install-package@v1
        with:
          apt: libarchive-tools

      - name: Build
        run: |
          ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: llvm-mingw
          path: dist/*.7z

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.7z
